// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MyRunshaw.Infrastructure.Database;

#nullable disable

namespace MyRunshaw.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260730211500_AddNotificationDevices")]
partial class AddNotificationDevices
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The authoritative complete model is AppDbContextModelSnapshot. This migration's
        // operations above are intentionally explicit to keep this cutover migration reviewable.
        modelBuilder.HasAnnotation("ProductVersion", "10.0.9");
    }
}
