// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRunshaw.Domain.Entities;
using MyRunshaw.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyRunshaw.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731180510_SimplifyBusSubscriptions")]
    partial class SimplifyBusSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("BusStops");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.BlockedUser", b =>
                {
                    b.Property<string>("BlockerId")
                        .HasColumnType("character varying(11)");

                    b.Property<string>("BlockedId")
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BlockerId", "BlockedId");

                    b.HasIndex("BlockedId");

                    b.ToTable("BlockedUsers");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.Bus", b =>
                {
                    b.Property<string>("BusId")
                        .HasColumnType("text");

                    b.Property<string>("CurrentBay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MapsRouteUrl")
                        .HasColumnType("text");

                    b.Property<string>("RouteDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BusId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.BusSubscription", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("character varying(11)");

                    b.Property<string>("BusId")
                        .HasColumnType("text");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId", "BusId");

                    b.HasIndex("BusId");

                    b.ToTable("BusSubscriptions");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("character varying(11)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.InAppNotice", b =>
                {
                    b.Property<string>("NoticeId")
                        .HasColumnType("text");

                    b.Property<bool>("Android")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Ios")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("LinkText")
                        .HasColumnType("text");

                    b.Property<string>("MaxVersion")
                        .HasColumnType("text");

                    b.Property<string>("MinVersion")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NoticeId");

                    b.ToTable("InAppNotices");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.NotificationDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("BusNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("FcmToken")
                        .IsUnique();

                    b.HasIndex("StudentId", "DeviceId")
                        .IsUnique();

                    b.ToTable("NotificationDevices");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.TimetableCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimetableDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.User", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfilePicVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SignupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimetableUrl")
                        .HasColumnType("text");

                    b.HasKey("StudentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusStop", b =>
                {
                    b.HasOne("MyRunshaw.Domain.Entities.Bus", "Bus")
                        .WithMany("BusStops")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.BlockedUser", b =>
                {
                    b.HasOne("MyRunshaw.Domain.Entities.User", "Blocked")
                        .WithMany()
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyRunshaw.Domain.Entities.User", "Blocker")
                        .WithMany()
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.BusSubscription", b =>
                {
                    b.HasOne("MyRunshaw.Domain.Entities.Bus", "Bus")
                        .WithMany("Subscriptions")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyRunshaw.Domain.Entities.User", "Student")
                        .WithMany("BusSubscriptions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.FriendRequest", b =>
                {
                    b.HasOne("MyRunshaw.Domain.Entities.User", "Receiver")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyRunshaw.Domain.Entities.User", "Sender")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.NotificationDevice", b =>
                {
                    b.HasOne("MyRunshaw.Domain.Entities.User", "Student")
                        .WithMany("NotificationDevices")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.TimetableCache", b =>
                {
                    b.HasOne("MyRunshaw.Domain.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.Bus", b =>
                {
                    b.Navigation("BusStops");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MyRunshaw.Domain.Entities.User", b =>
                {
                    b.Navigation("BusSubscriptions");

                    b.Navigation("NotificationDevices");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
